test_name: Client errors

stages:
  - name: When there are no reports stored, return 404
    request:
      url: http://localhost:8080/api/v0/report
      method: GET
    response:
      status_code: 404
