test_name: Client errors

stages:
  - name: When there are no reports stored, return empty array
    request:
      url: http://localhost:8080/api/v0/report
      method: GET
    response:
      status_code: 200
      body:
        - !anything
