<?php

/**
 * Stink Reporter
 * Report when and where it stinks and query for past stinks.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Stink Reporter
 * @version 0.0.0
 */

$router->get('/', function () use ($router) {
    return $router->app->version();
});

/**
 * get play
 * Summary: Make a game
 * Notes: 
 */
$router->get('/api/play', 'PlayApi@play');

