<?php

/**
 * Stink Reporter
 * PHP version 7.2
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * Report when and where it stinks and query for past stinks.
 * The version of the OpenAPI document: 0.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the model.
 */
namespace OpenAPIServer\Model;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Model\Wind;

/**
 * WindTest Class Doc Comment
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Model\Wind
 */
class WindTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Wind"
     */
    public function testWind()
    {
        $testWind = new Wind();
        $namespacedClassname = Wind::getModelsNamespace() . '\\Wind';
        $this->assertSame('\\' . Wind::class, $namespacedClassname);
        $this->assertTrue(
            class_exists($namespacedClassname),
            sprintf('Assertion failed that "%s" class exists', $namespacedClassname)
        );
        $this->markTestIncomplete(
            'Test of "Wind" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "direction"
     */
    public function testPropertyDirection()
    {
        $this->markTestIncomplete(
            'Test of "direction" property in "Wind" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "speed"
     */
    public function testPropertySpeed()
    {
        $this->markTestIncomplete(
            'Test of "speed" property in "Wind" model has not been implemented yet.'
        );
    }

    /**
     * Test attribute "gustSpeed"
     */
    public function testPropertyGustSpeed()
    {
        $this->markTestIncomplete(
            'Test of "gustSpeed" property in "Wind" model has not been implemented yet.'
        );
    }

    /**
     * Test getOpenApiSchema static method
     * @covers ::getOpenApiSchema
     */
    public function testGetOpenApiSchema()
    {
        $schemaArr = Wind::getOpenApiSchema();
        $this->assertIsArray($schemaArr);
    }
}
