<?php

/**
 * Stink Reporter
 * Report when and where it stinks and query for past stinks.
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class PlayApi extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation play
     *
     * Make a game.
     *
     *
     * @return Http response
     */
    public function play()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['my_choice'])) {
            throw new \InvalidArgumentException('Missing the required parameter $my_choice when calling play');
        }
        $my_choice = $input['my_choice'];


        return response('How about implementing play as a get method ?');
    }
}
