name: Api test

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
       
   steps:
    - name: Checkout head
      uses: actions/checkout@v2
    - name: Install requirements
      working-directory: ./source
      run: composer update --no-dev --no-scripts
    - name: Delete unit tests
      working-directory: ./source
      run: rm -r ./test
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Prepare Database
      working-directory: ./infrastructure
      run: |
            docker run -v $(pwd)/sql:/commands --rm -d -p 3306:3306 --name mysql -e MYSQL_ROOT_PASSWORD=totallyunsafe mysql:5.7.28
            docker exec mysql mysql -p3306 -h127.0.0.1 -uroot -ptotallyunsafe --execute="\. /commands/create_tables.sql"
    - name: Prepare Api Tests
      working-directory: ./apitests
      run: pip install tavern
    - name: Run Api Tests
      working-directory: ./apitests
      run: ./run-api-tests.sh
