name: Api test

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
       
   steps:
    - name: Checkout head
      uses: actions/checkout@v2
    - name: Run the app
      run: docker-compose up -d
    - name: Install requirements
      run: docker-compose exec -d apache composer update --no-dev --no-scripts
    - name: Delete unit tests
      working-directory: ./source
      run: rm -r ./test
    - name: Run Api Tests
      run: docker-compose run -d tavern /apitests/run-api-tests.sh
