name: Code Quality Assurance

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
   services:     
    mysql:
      image: mysql:5.7.28
      env:
          MYSQL_DATABASE: stink_db
      ports:
          - 3306
      options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
   steps:
    - name: Checkout head
      uses: actions/checkout@v2
    - name: Install requirements
      working-directory: ./source
      run: composer update
    - name: Unit Tests
      working-directory: ./source
      run: composer test
    - name: Linting
      working-directory: ./source
      run: composer phpcs
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Prepare Database
      working-directory: ./infrastructure
      run: mysql -uroot -proot--execute="\. /sql/create_tables.sql"
    - name: Prepare Api Tests
      working-directory: ./apitests
      run: |
            sudo apt-get install dos2unix
            dos2unix ./*
            chmod +x ./run-api-tests.sh
            pip install tavern
    - name: Run Api Tests
      working-directory: ./apitests
      run: ./run-api-tests.sh
