name: Code Quality Assurance

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout head
        uses: actions/checkout@v2
      - name: Run the app
        run: docker-compose up
      - name: Install requirements
        run: docker-compose exec apache composer update
      - name: Unit Tests
        run: docker-compose exec apache composer test
      - name: Linting
        working-directory: ./source
        run: docker-compose exec apache composer phpcs
