name: Code Quality Assurance

on: [push]

jobs:
  test:
   runs-on: ubuntu-latest
       
   steps:
    - name: Checkout head
      uses: actions/checkout@v2
    - name: Install requirements
      working-directory: ./source
      run: composer update
    - name: Unit Tests
      working-directory: ./source
      run: composer test
    - name: Linting
      working-directory: ./source
      run: composer phpcs
