<?php

/**
 * Address
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Address
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Address implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "city", "country", "number", "street", "zip" ],
  "type" : "object",
  "properties" : {
    "street" : {
      "type" : "string",
      "example" : "Garibaldistraße"
    },
    "number" : {
      "type" : "string",
      "example" : "7 A"
    },
    "zip" : {
      "type" : "string",
      "enum" : [ "13158" ]
    },
    "city" : {
      "type" : "string",
      "enum" : [ "Berlin" ]
    },
    "country" : {
      "type" : "string",
      "enum" : [ "Germany" ]
    }
  }
}
SCHEMA;

    /** @var string $street */
    private $street;

    /** @var string $number */
    private $number;

    /** @var string $zip */
    private $zip;

    /** @var string $city */
    private $city;

    /** @var string $country */
    private $country;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
