<?php

/**
 * BaseReport
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * BaseReport
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class BaseReport implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "location", "stink" ],
  "type" : "object",
  "properties" : {
    "location" : {
      "$ref" : "#/components/schemas/baseReport_location"
    },
    "stink" : {
      "$ref" : "#/components/schemas/stink"
    }
  },
  "description" : "The report of a notable stink event"
}
SCHEMA;

    /** @var \OpenAPIServer\Model\BaseReportLocation $location */
    private $location;

    /** @var \OpenAPIServer\Model\Stink $stink */
    private $stink;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
