<?php

/**
 * GameResult
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * GameResult
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class GameResult implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "properties" : {
    "serversChoice" : {
      "$ref" : "#/components/schemas/choices"
    },
    "playersChoice" : {
      "$ref" : "#/components/schemas/choices"
    },
    "winner" : {
      "type" : "string",
      "description" : "Who won the game",
      "enum" : [ "server", "player" ]
    }
  }
}
SCHEMA;

    /** @var \OpenAPIServer\Model\Choices $serversChoice */
    private $serversChoice;

    /** @var \OpenAPIServer\Model\Choices $playersChoice */
    private $playersChoice;

    /** @var string $winner Who won the game*/
    private $winner;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
