<?php

/**
 * ReportOutput
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * ReportOutput
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ReportOutput implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "time", "wind" ],
  "type" : "object",
  "properties" : {
    "time" : {
      "type" : "string",
      "format" : "datetime",
      "example" : "2020-03-10T12:00:00Z"
    },
    "wind" : {
      "$ref" : "#/components/schemas/wind"
    }
  },
  "allOf" : [ {
    "$ref" : "#/components/schemas/baseReport"
  } ]
}
SCHEMA;

    /** @var string $time */
    private $time;

    /** @var \OpenAPIServer\Model\Wind $wind */
    private $wind;

    /** @var \OpenAPIServer\Model\BaseReportLocation $location */
    private $location;

    /** @var \OpenAPIServer\Model\Stink $stink */
    private $stink;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
