<?php

/**
 * Report
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * Report
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class Report implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "location", "reporter", "stink", "time" ],
  "type" : "object",
  "properties" : {
    "time" : {
      "type" : "string",
      "format" : "datetime",
      "example" : "2020-03-10T12:00:00Z"
    },
    "location" : {
      "type" : "object",
      "anyOf" : [ {
        "$ref" : "#/components/schemas/address"
      }, {
        "$ref" : "#/components/schemas/coordinates"
      } ]
    },
    "stink" : {
      "$ref" : "#/components/schemas/stink"
    },
    "reporter" : {
      "$ref" : "#/components/schemas/reporter"
    }
  },
  "description" : "The report of a notable stink event"
}
SCHEMA;

    /** @var string $time */
    private $time;

    /** @var AnyOfAddressCoordinates $location */
    private $location;

    /** @var \OpenAPIServer\Model\Stink $stink */
    private $stink;

    /** @var \OpenAPIServer\Model\Reporter $reporter */
    private $reporter;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
