<?php

/**
 * ReportInput
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * ReportInput
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class ReportInput implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "reporter" ],
  "type" : "object",
  "properties" : {
    "reporter" : {
      "$ref" : "#/components/schemas/reporter"
    }
  },
  "allOf" : [ {
    "$ref" : "#/components/schemas/baseReport"
  } ]
}
SCHEMA;

    /** @var \OpenAPIServer\Model\Reporter $reporter */
    private $reporter;

    /** @var \OpenAPIServer\Model\BaseReportLocation $location */
    private $location;

    /** @var \OpenAPIServer\Model\Stink $stink */
    private $stink;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
