<?php

/**
 * TimeFrame
 *
 * PHP version 7.1
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 */
namespace OpenAPIServer\Model;

use OpenAPIServer\Interfaces\ModelInterface;

/**
 * TimeFrame
 *
 * @package OpenAPIServer\Model
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */
class TimeFrame implements ModelInterface
{
    private const MODEL_SCHEMA = <<<'SCHEMA'
{
  "required" : [ "endTime", "startTime" ],
  "type" : "object",
  "properties" : {
    "startTime" : {
      "type" : "string",
      "format" : "date-time"
    },
    "endTime" : {
      "type" : "string",
      "format" : "date-time"
    }
  }
}
SCHEMA;

    /** @var \DateTime $startTime */
    private $startTime;

    /** @var \DateTime $endTime */
    private $endTime;

    /**
     * Returns model schema.
     *
     * @param bool $assoc When TRUE, returned objects will be converted into associative arrays. Default FALSE.
     *
     * @return array
     */
    public static function getOpenApiSchema($assoc = false)
    {
        return json_decode(static::MODEL_SCHEMA, $assoc);
    }
}
